export default {
  IS_ALERT_VISIBLE: 'IS_ALERT_VISIBLE',
  IS_MOBILE: 'IS_MOBILE',
  IS_LEFT_NAV_VISIBLE: 'IS_LEFT_NAV_VISIBLE',
  PROJECTS_SELECTED_ITEM: 'PROJECTS_SELECTED_ITEM',
  PROJECTS_SELECTED_ELEMENT_ID: 'PROJECTS_SELECTED_ELEMENT_ID',
  PROJECTS_SELECTED_SUB_ITEM: 'PROJECTS_SELECTED_SUB_ITEM',
};
